server:
  port: 80

spring:
  application:
    name: place_order
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.18.128:8848
  rabbitmq:
    host: 192.168.18.128
    port: 5672
    username: mock-mall
    password: mock-mall
    virtual-host: /mock-mall